# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Release

on:
  workflow_dispatch

jobs:
  setup:
    name: Setup
    uses: tlslink/sslcon/.github/workflows/release-setup.yml@main
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [linux, windows, macos, macos-arm64]
        include:
        - build: linux
          os: ubuntu-20.04
          go: 'stable'
          archive-name: libopensocks-linux-amd64.tar.gz
        - build: windows
          os: windows-2019
          go: 'stable'
          archive-name: libopensocks-windows10-amd64.7z
        - build: macos
          os: macos-12
          go: 'stable'
          archive-name: libopensocks-macOS-amd64.tar.gz
        - build: macos-arm64
          os: macos-14
          go: 'stable'
          archive-name: libopensocks-macOS-arm64.tar.gz
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}
    - name: Build
      shell: bash
      run: |
        if [ "${{ matrix.build }}" = "linux" ]; then
          go build -trimpath -ldflags "-s -w" --buildmode=c-archive -o libopensocks.a libopensocks.go
          go build -trimpath -ldflags "-s -w" --buildmode=c-shared -o libopensocks.so libopensocks.go
        elif [ "${{ matrix.build }}" = "windows" ]; then
          go build -trimpath -ldflags "-s -w" --buildmode=c-archive -o libopensocks.a libopensocks.go
          go build -trimpath -ldflags "-s -w" --buildmode=c-shared -o libopensocks.dll libopensocks.go
        elif [ "${{ matrix.build }}" = "macos" ]; then
          go build -trimpath -ldflags "-s -w" --buildmode=c-archive -o libopensocks.a libopensocks.go
          go build -trimpath -ldflags "-s -w" --buildmode=c-shared -o libopensocks.so libopensocks.go
        elif [ "${{ matrix.build }}" = "macos-arm64" ]; then
          go build -trimpath -ldflags "-s -w" --buildmode=c-archive -o libopensocks.a libopensocks.go
          go build -trimpath -ldflags "-s -w" --buildmode=c-shared -o libopensocks.so libopensocks.go
        fi
    - name: Build archive
      shell: bash
      run: |
        # ls -lR
        if [ "${{ matrix.build }}" = "windows" ]; then
          7z a "${{ matrix.archive-name }}" libopensocks.dll libopensocks.a libopensocks.h
        else
          tar -czf "${{ matrix.archive-name }}" libopensocks.so libopensocks.a libopensocks.h
        fi
    - name: Continuous release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/heads/')
      with:
        prerelease: false
        files: |
          ${{ matrix.archive-name }}
        tag_name: continuous
        
    - if: startsWith(github.ref, 'refs/tags/')
      name: Tagged release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ${{ matrix.archive-name }}
        name: Release build (${{ github.ref_name }})
